### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by valentijnscholten** [robert-bor/aho-corasick#16]
Hi,

I am getting frequent NullPointerException inside Trie.java

    Caused by: java.lang.NullPointerException
    	at org.ahocorasick.trie.Trie.getState(Trie.java:138)
    	at org.ahocorasick.trie.Trie.parseText(Trie.java:99)

Looks like currentState can be null because failure() can return null?

        private State getState(State currentState, Character character) {
            State newCurrentState = currentState.nextState(character);
            while (newCurrentState == null) {
                currentState = currentState.failure();
                newCurrentState = currentState.nextState(character);
            }
            return newCurrentState;
        }

**Comment by sashavasko** [comment]
I'm guessing this is happening because you add new keywords after calling parseText or tokenize.
To fix that addKeyword needs to be modified to force failure states construction on next parseText : 
add
failureStatesConstructed = true;

at the end of Trie.addKeyword()

**Comment by mcarlsen** [comment]
It is also possible that there is a race condition in the the first invokation of parseText where multiple threads may enter constructFailureStates and cause mayhem.

A work-around that seems to work for me is to call parseText once - after all addKeyword are done and while still single-threaded - so that constructFailureStates is triggered exactly once.
